# Generated by Django 4.0.3 on 2022-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='myapp/img/default.jpg', null=True, upload_to=''),
        ),
    ]
